/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppleLogo: typeof import('./components/icons/AppleLogo.vue')['default']
    CategoryFilter: typeof import('./components/CategoryFilter.vue')['default']
    FacebookLogo: typeof import('./components/icons/FacebookLogo.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    GoogleLogo: typeof import('./components/icons/GoogleLogo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RestaurantCard: typeof import('./components/RestaurantCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialButton: typeof import('./components/SocialButton.vue')['default']
    UberButton: typeof import('./components/UberButton.vue')['default']
    UberInput: typeof import('./components/UberInput.vue')['default']
  }
}
